### ISSUE TITLE
Incorrect handling of characters like €, Ä,Ö,Ü,ä,ö,ü

### ISSUE THREAD

**Issue by wgemm** [posit-dev/py-shinylive#28]
When I deploy my project with shinylive I get problems with the character handling. This issue was fixed in shiny with the last version. But the webassembly still can't handle it.

Running it with shiny
![grafik](https://github.com/posit-dev/py-shinylive/assets/7580771/1a5d2c3f-6b39-47b8-ac49-b5d1a2c09ea0)

Running as webassembly
![grafik](https://github.com/posit-dev/py-shinylive/assets/7580771/0d4e8c8c-eb14-49b2-9beb-aefac8ec207a)

**Comment by wch** [comment]
What platform are you deploying from? If it is Windows, I have an idea of what might be going on.

**Comment by wgemm** [comment]
I am deploying from Windows 10

**Comment by wch** [comment]
I made a potential fix in #29.

Does it work if you install with the following command and then deploy again?

```
pip install git+https://github.com/posit-dev/py-shinylive.git@windows-encoding --force-reinstall
```

**Comment by wgemm** [comment]
Thanks a lot. I have tested the branch the version works fine for me!

**Comment by wch** [comment]
Great!
