### ISSUE TITLE
Where can I find the Pyodide version currently in use?

### ISSUE THREAD

**Issue by darrida** [posit-dev/py-shinylive#37]
Hi there. We are using Shinylive for internal utilities, and I like it quite a bit -- enough so that I'm working on utilities to make it easier for us to use it (i.e., [py-shinylive-deploy-webserver](https://github.com/darrida/py-shinylive-deploy-webserver), [py-shinylive-authentication](https://github.com/darrida/py-shinylive-authentication) -- early stages, none-existent or incomplete readme files, etc).

I'm working on improving our internal documentation for setting and maintaining local workstation dev environments so that when we build and test with regular Shiny initially (feedback loop is quicker than Shinylive, so we work on that after main functionality is complete) the dev environments are sufficiently similar to the real Shinylive environment. 

My docs include information regarding pinning `shiny` and `shinylive` versions, pinning the correct version of packages that have to be installed locally that are already in shinylive (i.e., `pydantic<2.0`, etc).

We are linking to the Python Shinylive docs page for a list of packages, but I'm also interested where in this repo I can locate the actual `pyodide` version used with a given Shinylive version, so I can link to that packages page as well. Reason being that the Shiny docs sometimes lag behind version updates a little (you all do a great job at this; just trying to prevent confusion for team members not as familiar with Shiny and Shinylive in the future).

I've looked as best as I can across the repos for py-shiny and py-shinylive and can't find any reference to actual Pyodide version in use for a given Shinylive version. I can find the reference on the Python Shinylive docs page, but can't find where that's located in the docs GitHub source for that either.

My apologies if I overlooked something obvious, but any assistance with where that is pinned, stated, etc, would be great.

**Comment by gadenbuie** [comment]
Thanks for sharing those projects, we'll be excited to check them out!

The py-shinylive package is basically a utility package to facilitate exporting apps into shinylive. The main shinylive web assets, including pyodide and pre-built packages, is over in https://github.com/posit-dev/shinylive. The Makefile records [the version of pyodide in use](https://github.com/posit-dev/shinylive/blob/1ce625f5bcfdb27279de056790dd9510ff899601/Makefile#L20). We also pre-build a set of packages and record their versions in [shinylive_lock.json](https://github.com/posit-dev/shinylive/blob/main/shinylive_lock.json).

**Comment by darrida** [comment]
Appreciate the quite reply! 

Now that you point the Makefile out, it seems obvious. I had looked through the Makefile previously, but missed the pyodide reference -- it's possible I spelled it wrong when doing a word search.

And the lock file as a good reference for shinylive's additional packages is helpful too. I looked at it previously, but was mainly looking for the pyodide version, so didn't connect the dots with the helpful information it does contain.

**Comment by wch** [comment]
Just one more piece of information that might be useful:

The base pyodide distribution comes with a file named pyodide-lock.json, which lists the versions of all included packages. When we build shinylive, we modify this file by merging in our shinylive_lock.json file.

This modified file is generated at build time and is not committed to the repository, but you can see the current version of it at https://shinylive.io/py/shinylive/pyodide/pyodide-lock.json. (Note that shinylive.io is deployed from the `deploy` branch of this repository, and not `main`.)

**Comment by darrida** [comment]
Also very helpful. Thanks!
